version: 2
updates:
- package-ecosystem: nuget
  directory: "/Selenium.Axe"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  commit-message:
    prefix: chore
- package-ecosystem: npm
  directory: "/Selenium.Axe/Selenium.Axe"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  commit-message:
    prefix: chore
