configuration: Release
image: Visual Studio 2015
#restore NuGet
before_build:
    - nuget restore Globant.Selenium.Axe\Globant.Selenium.Axe.sln

#build solution
build:
    project: Globant.Selenium.Axe\Globant.Selenium.Axe.sln
    verbosity: normal
    publish_wap: true

artifacts:
    - path: '**\*.nupkg' # find all NuGet packages recursively

#Push to nuget
deploy:
    provider: NuGet
    api_key:
        secure: wO5eiWkOc3xv1qM1mChKx6weYq9h795U6u5NJg6kqwdSgsXZVCXjQJk6G05MuPKC
    skip_symbols: false
    artifact: /.*\.nupkg/