configuration: Release

#restore NuGet
before_build:
    - nuget restore Globant.Selenium.Axe\Globant.Selenium.Axe.sln

#build solution
build:
    project: Globant.Selenium.Axe\Globant.Selenium.Axe.sln
    verbosity: normal
    publish_wap: true

#Push to nuget
deploy:
    provider: NuGet
    api_key:
        secure: x/JdMSCp+xijmT0uyFZm4eWjZWlU+aaviayOAK8PwCHioJ/rbKNp59PrTTG6MWwB
    skip_symbols: false
    artifact: /.*\.nupkg/