configuration: Release
image: Visual Studio 2017
version: %appveyor_build_version%

#restore NuGet
before_build:
    - nuget restore Globant.Selenium.Axe\Globant.Selenium.Axe.sln
    - appveyor UpdateBuild -Version {version}

#build solution
build:
    project: Globant.Selenium.Axe\Globant.Selenium.Axe.sln
    verbosity: normal
    publish_wap: true

after_build:
    - appveyor PushArtifact Globant.Selenium.Axe.%appveyor_build_version%.nupkg

#tests
test:
  # all except categories to test
  categories:
    except:
      - Integration
    
#Push to nuget
deploy:
    provider: NuGet
    api_key:
        secure: wO5eiWkOc3xv1qM1mChKx6weYq9h795U6u5NJg6kqwdSgsXZVCXjQJk6G05MuPKC
    skip_symbols: false
    artifact: /.*\.nupkg/
    
only_commits:
  files:
    - Globant.Selenium.Axe/