configuration: Release
image: Visual Studio 2017
#restore NuGet
before_build:
    - nuget restore Globant.Selenium.Axe\Globant.Selenium.Axe.sln

#build solution
build:
    project: Globant.Selenium.Axe\Globant.Selenium.Axe.sln
    verbosity: normal
    publish_wap: true

after_build:
    - nuget pack Globant.Selenium.Axe\Globant.Selenium.Axe\Globant.Selenium.Axe.nuspec -Version %appveyor_build_version%
    - appveyor PushArtifact Globant.Selenium.Axe.%appveyor_build_version%.nupkg

#tests
test:
  # all except categories to test
  categories:
    except:
      - Integration
    
#Push to nuget
deploy:
    provider: NuGet
    api_key:
        secure: wO5eiWkOc3xv1qM1mChKx6weYq9h795U6u5NJg6kqwdSgsXZVCXjQJk6G05MuPKC
    skip_symbols: false
    artifact: /.*\.nupkg/