name: ci-$(Date:yyyyMMdd)$(Rev:-r)

pool:
  vmImage: windows-2019

variables:
  versionSuffix: $(Build.BuildNumber)
  buildConfiguration: 'Release'
  solutionDirectory: '$(System.DefaultWorkingDirectory)/Selenium.Axe'
  outputDirectory: '$(solutionDirectory)/Selenium.Axe/bin/$(buildConfiguration)'

steps:
- task: DotNetCoreInstaller@1
  inputs:
    version: '2.2.401'

- script: dotnet restore
  displayName: dotnet restore
  workingDirectory: $(solutionDirectory)

- script: dotnet build --no-restore -c $(buildConfiguration) --version-suffix $(versionSuffix)
  displayName: dotnet build
  workingDirectory: $(solutionDirectory)

- script: dotnet test --no-restore -l:trx;LogFileName=$(System.DefaultWorkingDirectory)/dotnet-test-results.xml
  displayName: dotnet test
  workingDirectory: $(solutionDirectory)

- task: PublishTestResults@2
  displayName: publish test results
  inputs:
      testResultsFiles: $(System.DefaultWorkingDirectory)/dotnet-test-results.xml
      testRunTitle: dotnet test
  condition: succeededOrFailed()

- publish: $(outputDirectory)
  displayName: publish drop
  name: drop
