name: ci-$(Date:yyyyMMdd)$(Rev:-r)

pool:
  vmImage: windows-2019

variables:
  version: '1.3.0'
  buildConfiguration: 'Release'
  solutionDirectory: '$(System.DefaultWorkingDirectory)/Selenium.Axe'
  outputDirectory: '$(solutionDirectory)/Selenium.Axe/bin/$(buildConfiguration)'

steps:
- task: DotNetCoreInstaller@1
  inputs:
    version: '2.2.401'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'troywalshprof'
    scannerMode: 'MSBuild'
    projectKey: 'TroyWalshProf_SeleniumAxeDotnet'
    projectName: 'SeleniumAxeDotnet'

- task: NodeTool@0
  inputs:
    versionSpec: '10.16.2'
  displayName: use node 10.16.2

- script: dotnet restore
  displayName: dotnet restore
  workingDirectory: $(solutionDirectory)

- script: dotnet build --no-restore -c $(buildConfiguration) -p:Version=$(version)
  displayName: dotnet build
  workingDirectory: $(solutionDirectory)

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(solutionDirectory)\Selenium.Axe.Test\Selenium.Axe.Test.csproj'
    arguments: '--collect:"Code Coverage"'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- publish: $(outputDirectory)
  displayName: publish drop
  name: drop
