version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    version_requirement_updates: 'increase_versions'
    default_labels:
      - 'dependencies'
    commit_message:
      prefix: 'chore'
                
  - package_manager: 'dotnet:nuget'
    directory: '/'
    update_schedule: 'daily'
    default_labels:
      - 'dependencies'
    commit_message:
      prefix: 'chore'
