name: .NET Core

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: mkdir -p artifactApp
    - run: mkdir -p artifactTests

    - uses: actions/checkout@master
    - name: Get Latest Release
      id: latest_version
      uses: abatilo/release-info-action@v1.1.0
      with:
        owner: abatilo
        repo: release-info-action
    - name: Example of consumption of the output
      env:
        LATEST: ${{ steps.latest_version.outputs.latest_tag }}
        LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
      run: |
        echo "Version $LATEST was released at $LATEST_DATE"

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
   
    - name: Install dependencies
      run: dotnet restore Selenium.Axe/Selenium.Axe.sln
   
    - name: Build
      run: dotnet build Selenium.Axe/Selenium.Axe.sln --configuration Release --no-restore
    
    - name: Update Chrome
      run: choco upgrade googlechrome
    
    - name: Update Firefox
      run: choco upgrade firefox
    
    - name: Test
      run: dotnet test Selenium.Axe/Selenium.Axe.sln --no-restore --verbosity normal --logger "trx" --results-directory ${{github.workspace}}/artifactTests
    
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: lowerTestResults
        path: artifactTests\logs
  
    - uses: release-drafter/release-drafter@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
